### ISSUE TITLE
Verificar necessidade de siglas multivaloradas na Instituição de Ensino Superior

### ISSUE THREAD

**Issue by Lvght** [Lvght/e-andifes#25]
No arquivo abaixo nós permitimos que Instituições de Ensino possuam mais de uma sigla. Isso é realmente um requisito da aplicação?

https://github.com/Lvght/e-andifes/blob/5f4a6755e591dfdce854efa1f3e61fd7abf9f6a7/sql/sigla_instituicao_superior.sql

**Comment by PedroGSantos** [comment]
Acredito que isso foi feito na etapa de normalização, o @hiperbrainer sabe explicar melhor, mas foi por causa que naquela etapa estavamos usando uma chave primária composta (**nome e campus**) para a IES, e nisso a sigla só dependia do nome, por isso foi feito essa separação com o intuito de normalizar na 2º forma. Agora que estamos usando surrogates, isso pode mudar. Uma questão importante é que do jeito que foi modelado, cada campus de uma mesma universidade terá seu próprio registro na tabela IES, mas eles compartilham a mesma sigla (acho que do jeito que foi mandado até agr ta errado até pq a FK ta na tabela sigla e não na IES, não percebemos isso)

Acredito que podemos usar uma das duas alternativas, essa:

```
CREATE TABLE sigla_instituicao_superior (
    sigla VARCHAR(10) PRIMARY KEY NOT NULL UNIQUE,
);

CREATE TABLE instituicao_ensino_superior
(
    id                 SERIAL PRIMARY KEY,
    nome_completo      VARCHAR(100) NOT NULL,
    campus             VARCHAR(50) NOT NULL,
    tem_NucLi          BOOLEAN NOT NULL,
    e_polo             BOOLEAN NOT NULL, 
    contato_reitoria   VARCHAR(50),
    FK_IES_sigla          VARCHAR(10) NOT NULL,
    FK_id_endereco     INT NOT NULL,

    CONSTRAINT fk_ies_sigla
        FOREIGN KEY (FK_IES_sigla)
            REFERENCES sigla_instituicao_superior (sigla)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
            
     CONSTRAINT fk_endereco
        FOREIGN KEY (FK_id_endereco)
            REFERENCES endereco  (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    CONSTRAINT unique_nome_campus
        UNIQUE (nome_completo, campus)

);
``` 

ou colocar a sigla na tabela IES mesmo:

```
CREATE TABLE instituicao_ensino_superior
(
    id                 SERIAL PRIMARY KEY,
    nome_completo      VARCHAR(100) NOT NULL,
    campus             VARCHAR(50) NOT NULL,
    tem_NucLi          BOOLEAN NOT NULL,
    e_polo             BOOLEAN NOT NULL, 
    contato_reitoria   VARCHAR(50),
    sigla          VARCHAR(10) NOT NULL,
    FK_id_endereco     INT NOT NULL,
   
     CONSTRAINT fk_endereco
        FOREIGN KEY (FK_id_endereco)
            REFERENCES endereco  (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    CONSTRAINT unique_nome_campus
        UNIQUE (nome_completo, campus)
);
```

**Comment by PedroGSantos** [comment]
Vou fazer a primeira opção
